Attribute VB_Name = "m_constants"
Option Explicit

Public Const OPERATION_PATH     As String = "/subSUB_FIRSTLINE:SAPLMIGO:0011/cmbGODYNPRO-ACTION"
Public Const REF_DOC_PATH       As String = "/subSUB_FIRSTLINE:SAPLMIGO:0011/cmbGODYNPRO-REFDOC"

Public Const RSRV_NUM_PATH          As String = "/subSUB_FIRSTLINE:SAPLMIGO:0011/subSUB_FIRSTLINE_REFDOC:SAPLMIGO:2080/txtGODYNPRO-RESERVATION_NUMBER"
Public Const RSRV_POS_PATH          As String = "/subSUB_FIRSTLINE:SAPLMIGO:0011/subSUB_FIRSTLINE_REFDOC:SAPLMIGO:2080/txtGODYNPRO-RESERVATION_ITEM"
Public Const DOC_MAT_PATH           As String = "/subSUB_HEADER:SAPLMIGO:0101/subSUB_HEADER:SAPLMIGO:0100/tabsTS_GOHEAD/tabpOK_GOHEAD_GENERAL/ssubSUB_TS_GOHEAD_GENERAL:SAPLMIGO:0112/txtGOHEAD-MTSNR"
Public Const TEXT_HEADER_DOC_PATH   As String = "/subSUB_HEADER:SAPLMIGO:0101/subSUB_HEADER:SAPLMIGO:0100/tabsTS_GOHEAD/tabpOK_GOHEAD_GENERAL/ssubSUB_TS_GOHEAD_GENERAL:SAPLMIGO:0112/txtGOHEAD-BKTXT"
Public Const MOVE_TYPE_PATH         As String = "/subSUB_FIRSTLINE:SAPLMIGO:0011/ctxtGODEFAULT_TV-BWART"
Public Const MOVE_TYPE_CONT_PATH    As String = "/subSUB_FIRSTLINE:SAPLMIGO:0011/ctxtGODEFAULT_TV-SOBKZ"
Public Const DOC_DATE_PATH          As String = "/subSUB_HEADER:SAPLMIGO:0101/subSUB_HEADER:SAPLMIGO:0100/tabsTS_GOHEAD/tabpOK_GOHEAD_GENERAL/ssubSUB_TS_GOHEAD_GENERAL:SAPLMIGO:0112/ctxtGOHEAD-BLDAT"
Public Const POST_DATE_PATH         As String = "/subSUB_HEADER:SAPLMIGO:0101/subSUB_HEADER:SAPLMIGO:0100/tabsTS_GOHEAD/tabpOK_GOHEAD_GENERAL/ssubSUB_TS_GOHEAD_GENERAL:SAPLMIGO:0112/ctxtGOHEAD-BUDAT"
Public Const QTY_PATH               As String = "/subSUB_ITEMDETAIL:SAPLMIGO:0301/subSUB_DETAIL:SAPLMIGO:0300/tabsTS_GOITEM/tabpOK_GOITEM_QUANTITIES/ssubSUB_TS_GOITEM_QUANTITIES:SAPLMIGO:0315/txtGOITEM-ERFMG"
Public Const POS_OK_PATH            As String = "/subSUB_ITEMDETAIL:SAPLMIGO:0301/subSUB_DETAIL:SAPLMIGO:0300/subSUB_DETAIL_TAKE:SAPLMIGO:0304/chkGODYNPRO-DETAIL_TAKE"
Public Const DOVER_FIO_PATH         As String = "/subSUB_HEADER:SAPLMIGO:0101/subSUB_HEADER:SAPLMIGO:0100/tabsTS_GOHEAD/tabpOK_GOHEAD_EXT_2/ssubSUB_TS_GOHEAD_EXT_2:SAPLZP2_MIGO_BADI_POA:9001/txtZP2_D_PWR_ATTRN-ZZ_NAME"

Public Const EXECUTE_PATH       As String = "wnd[0]/tbar[1]/btn[23]"

Public Const ERROR_WINDOW_INFS_BTN_PATH         As String = "wnd[1]/tbar[0]/btn[19]"
Public Const ERROR_WINDOW_WRN_BTN_PATH          As String = "wnd[1]/tbar[0]/btn[18]"
Public Const ERROR_WINDOW_ERROR_BTN_PATH        As String = "wnd[1]/tbar[0]/btn[17]"
Public Const ERROR_WINDOW_STOP_BTN_PATH         As String = "wnd[1]/tbar[0]/btn[16]"
Public Const ERROR_WINDOW_ERROR_ICON_PATH       As String = "wnd[1]/usr/lbl[1,@]"
Public Const ERROR_WINDOW_ERROR_TEXT_PATH       As String = "wnd[1]/usr/lbl[10,@]"
Public Const ERROR_WINDOW_BTN_OK_PATH           As String = "wnd[1]/tbar[0]/btn[0]"


